### PR TITLE
[WIP] Docker

### PR DESCRIPTION
**Pull request by niccokunzmann**
I would like to run these services inside a docker container. This is what I tried.

Currently, I wonder why the migrations are running without a connection to the database server.

I think, I better share this in case people are looking for it.

Either I get:

```
badgr_1  | django.db.utils.OperationalError: (1049, "Unknown database 'badgr'")
```

or it hangs after the migrations are done:

```
badgr_1  |   Applying socialaccount.0003_extra_data_default_dict... OK
badgr_1  | System check identified some issues:
badgr_1  | 
badgr_1  | WARNINGS:
badgr_1  | ?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG, TEMPLATE_LOADERS.
badgr_1  | ?: (urls.W002) Your URL pattern '^/(?P<pathway_slug>[^/]+)$' [name='pathway_detail'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
badgr_1  | ?: (urls.W002) Your URL pattern '^/(?P<pathway_slug>[^/]+)/completion/(?P<element_slug>[^/]+)$' [name='pathway_completion_detail'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
badgr_1  | ?: (urls.W002) Your URL pattern '^/(?P<pathway_slug>[^/]+)/elements$' [name='pathway_element_list'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
badgr_1  | ?: (urls.W002) Your URL pattern '^/(?P<pathway_slug>[^/]+)/elements/(?P<element_slug>[^/]+)$' [name='pathway_element_detail'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
badgr_1  | ?: (urls.W002) Your URL pattern '^/?$' [name='pathway_list'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.
badgr_1  | 
badgr_1  | System check identified 6 issues (0 silenced).

```

### CODE REVIEW

**Comment by ottonomy** [comment]
@niccokunzmann Thanks for looking into this. Docker is definitely a viable delivery mechanism for badgr-server. Let us know when this is ready for review.

**Comment by niccokunzmann** [comment]
I solved the error with the database. I am quite fine with this service. There is a pull request over at https://github.com/concentricsky/badgr-ui/pull/48 where I do not see the styling of the page in the docker image.
Also, I can log into locahost:8000/staff and I am able to log into the front page. :+1:

**Comment by shingom** [comment]
it's nice. but i face this error when i was trying to execute 'docker-compose up'.
```
Pulling ui (badgr-ui:)...
ERROR: pull access denied for badgr-ui, repository does not exist
```

**Comment by ottonomy** [comment]
@niccokunzmann thanks for the contribution! We now have merged a python3 + docker implementation using docker-compose to the develop branch. We looked at your code as part of developing this work. If you have a chance, I'd love to hear your thoughts/review.

**Pull request closed without merging**
