### PR TITLE
Updates for python3 compatability

### PR DESCRIPTION
**Pull request by garrettseward**

### CODE REVIEW

**Comment by garrettseward** [comment]
This is waiting on pull requests for `django-cachemodel`, `apispec-djangorestframework`, `django-basic-models`, and `openbadges-bakery` to be merged (and subsequent PyPi entries updated).

**Comment by frgray** [comment]
@garrettseward I have updated and uploaded all required libraries to PyPi.

**Comment by shingom** [comment]
It's gonna be a long load.

**Comment by shingom** [comment]
to make clear.
python2 is going not to be supported.
Django1.11 is going to end support within two months.
Django2 doesn't support python2 anyway.#208

**Pull request merged**
